### ISSUE TITLE
!d timer does not work 

### ISSUE THREAD

**Issue by YelsewB** [codeplexnl/slack-spotify-bot#9]
Ying tries to delete an item from the queue but get's the message he already used the command in the last 15 minutes. As you can see in the log this was not the case.

Please fix.

> Spot BotAPP [10:59] Gareth Gates - Anyone Of Us (Stupid Mistake)
> [11:02] Macklemore & Ryan Lewis;Wanz - Thrift Shop (feat. Wanz)
> [11:06] Jamiroquai - Canned Heat
> Spot BotAPP [11:12] Jimi Hendrix - Voodoo Child (Slight Return)
> Spot BotAPP [11:17] Sammy Dread - M16
> Wesley [11:18] !q
> Spot BotAPP [11:18]  First 5 numbers in the queue
> 1. Delroy Wilson - I'll Never Hurt You
> 2. Feng Suave - By the Poolside
> 3. Elton John - Rocket Man (I Think It's Going To Be A Long Long Time)
> 4. John Mayer - Wildfire
> 5. Waldeck - Memories
> Wesley [11:18] !next
> Spot BotAPP [11:18] Delroy Wilson - I'll Never Hurt You
> Ying [11:18] !q
> Spot BotAPP [11:18] First 5 numbers in the queue
> 1. Feng Suave - By the Poolside
> 2. Elton John - Rocket Man (I Think It's Going To Be A Long Long Time)
> 3. John Mayer - Wildfire
> 4. Waldeck - Memories
> 5. Jay & The Americans - Come A Little Bit Closer
> Ying [11:18] !d 1
> Spot BotAPP [11:18] Already skipped or deleted a song from the queue in the last 15 minutes. Try again later]

**Comment by ykz89** [comment]
Should be fixed with #10

**Comment by codeplexnl** [comment]
Fixed
